"""Update population schema

Revision ID: 5818c976ec7d
Revises: d8b5bf74221e
Create Date: 2021-09-19 09:38:44.929902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5818c976ec7d'
down_revision = 'd8b5bf74221e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('population', sa.Column('pop_12', sa.Integer(), nullable=True, comment='Total state population ages >= 12'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('population', 'pop_12')
    # ### end Alembic commands ###
