"""Update vax_malaysia and vax_state schema

Revision ID: 9fde3d4af686
Revises: 5818c976ec7d
Create Date: 2021-09-19 09:55:25.982865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fde3d4af686'
down_revision = '5818c976ec7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vax_malaysia', sa.Column('cumul_partial_child', sa.Integer(), nullable=True, comment='Sum of cumulative partial doses delivered for children until row date'))
    op.add_column('vax_malaysia', sa.Column('cumul_full_child', sa.Integer(), nullable=True, comment='Sum of cumulative full doses delivered for childred until row date'))
    op.add_column('vax_state', sa.Column('cumul_partial_child', sa.Integer(), nullable=True, comment='Sum of cumulative partial doses delivered for children until row date'))
    op.add_column('vax_state', sa.Column('cumul_full_child', sa.Integer(), nullable=True, comment='Sum of cumulative full doses delivered for childred until row date'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vax_state', 'cumul_full_child')
    op.drop_column('vax_state', 'cumul_partial_child')
    op.drop_column('vax_malaysia', 'cumul_full_child')
    op.drop_column('vax_malaysia', 'cumul_partial_child')
    # ### end Alembic commands ###
