"""Add linelist_deaths schema

Revision ID: c11ac992c04a
Revises: ffec75dfdadd
Create Date: 2021-09-19 07:54:19.691798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11ac992c04a'
down_revision = 'ffec75dfdadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linelist_deaths',
    sa.Column('row_id', sa.Integer(), autoincrement=False, nullable=False, comment='Case ID'),
    sa.Column('row_version', sa.Integer(), nullable=True, comment='Row version'),
    sa.Column('date', sa.Date(), nullable=True, comment='Case date'),
    sa.Column('date_positive', sa.Date(), nullable=True, comment='Case date'),
    sa.Column('date_dose1', sa.Date(), nullable=True, comment='Case date'),
    sa.Column('date_dose2', sa.Date(), nullable=True, comment='Case date'),
    sa.Column('vaxtype', sa.Text(), nullable=True, comment='Vaccine name'),
    sa.Column('state', sa.Text(), nullable=True, comment='State name'),
    sa.Column('age', sa.Integer(), nullable=True, comment='Age'),
    sa.Column('male', sa.Integer(), nullable=True, comment='Gender (male if 1)'),
    sa.Column('bid', sa.Integer(), nullable=True, comment='Brought in dead'),
    sa.Column('malaysian', sa.Integer(), nullable=True, comment='Citizenship (Malaysian if 1)'),
    sa.Column('comorb', sa.Integer(), nullable=True, comment='With comorbidities?'),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linelist_deaths')
    # ### end Alembic commands ###
