"""Add aefi schema

Revision ID: d8b5bf74221e
Revises: c11ac992c04a
Create Date: 2021-09-19 09:20:02.909192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b5bf74221e'
down_revision = 'c11ac992c04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aefi',
    sa.Column('row_id', sa.Integer(), autoincrement=False, nullable=False, comment='Case ID'),
    sa.Column('row_version', sa.Integer(), nullable=True, comment='Row version'),
    sa.Column('date', sa.Date(), nullable=True, comment='Case date'),
    sa.Column('vaxtype', sa.Text(), nullable=True, comment='Vaccine name'),
    sa.Column('reports_mysj', sa.Integer(), nullable=True, comment='Number of AEFI reports through MySejahtera'),
    sa.Column('reports_npra', sa.Integer(), nullable=True, comment='Number of AEFI reports through NPRA website'),
    sa.Column('nonserious', sa.Integer(), nullable=True, comment='Number of non-serious AEFI reported'),
    sa.Column('serious', sa.Integer(), nullable=True, comment='Number of serious AEFI reported'),
    sa.Column('suspected_anaphylaxis', sa.Integer(), nullable=True, comment='Number of suspected anaphylaxis reported'),
    sa.Column('acute_facial_paralysis', sa.Integer(), nullable=True, comment='Number of acute facial paralysis reported'),
    sa.Column('venous_thromboembolism', sa.Integer(), nullable=True, comment='Number of venous thromboembolism reported'),
    sa.Column('myo_pericarditis', sa.Integer(), nullable=True, comment='Number of myopericarditis reported'),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aefi')
    # ### end Alembic commands ###
