"""Add tests_state schema

Revision ID: ffec75dfdadd
Revises: 7c85c1c7765b
Create Date: 2021-09-19 06:22:02.223375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffec75dfdadd'
down_revision = '7c85c1c7765b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests_state',
    sa.Column('row_id', sa.Integer(), autoincrement=False, nullable=False, comment='Tests UUID'),
    sa.Column('row_version', sa.Integer(), nullable=True, comment='Row version'),
    sa.Column('date', sa.Date(), nullable=True, comment='Reported date'),
    sa.Column('state', sa.Text(), nullable=True, comment='State name'),
    sa.Column('rtk_ag', sa.Integer(), nullable=True, comment='Total RTK-Ag tests performed'),
    sa.Column('pcr', sa.Integer(), nullable=True, comment='Total RT-PCR tests performed'),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests_state')
    # ### end Alembic commands ###
